### PR TITLE
added configuration for zulip installation url

### PR DESCRIPTION
**Pull request by m2ger**

### CODE REVIEW

**Comment by wdaher** [comment]
Hi @m2ger,

Thanks for the pull request! I'lll take a more detailed look at it later this week, but here are my two requests:

1. Can we axe the "subdomain" configuration option and just use this one instead, while we're in here? (I think no one is currently using the "subdomain" option, so I'd like to eliminate it (since anything you can do with it, you can do with this more general one).

2. Thoughts on having the user just specify the hostname of the Zulip server, rather than the complete URL? It seems like I, sysadmin-configuring-this, shouldn't have to think too hard/worry about the exact URL endpoint that the Zulip server uses for its API. (There's also some virtue in hardcoding /api/v1/, since as of this writing, this plugin only speaks /api/v1 anyway.)

Thoughts on those two changes? If you're able to make them, I'd love to merge this PR!

Thanks,
Waseem

**Comment by m2ger** [comment]
Hi @wdaher 

I left the subdomain option just to be backwards compatible, but if it is not used then of course this does not make any sense to keep it. And good point on the endpoint too. I'll fix those.

regards,
Indrek

**Comment by wdaher** [comment]
Hi @m2ger , sorry for the delay in my response on this! I will take a look by the end of the weekend at the latest.

**Comment by wdaher** [comment]
This looks good to me.
I've made a small change (to make it so that the default server is zulip.com if you don't specify one, for backwards-compatibility) and am testing and building it now. If it all goes well, I'll merge it later today.

Thanks!

**Comment by wdaher** [comment]
OK, I've merged this pull request, with some slight modifications.
I'll next work on releasing a new version of the plugin so that you can get it directly from the Jenkins plugin directory.

**Comment by m2ger** [comment]
Thanks!

I guess the documentation needs to be updated in https://zulip.com/integrations/#jenkins too.

**Pull request closed without merging**
